config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :weekly_schedules

  resources :airports do
    resources :positions
    resources :operations do
      get 'send_to_dashboard', on: :member
    end
    resources :adhoc_cancellations
    resources :flights
    resources :flight_schedules
    resources :turns
    resources :arrivals
    resources :airplanes
    resources :departures
    resources :employees
    resources :metrics
    resources :tickers do 
      post 'edit_individual', on: :collection 
      put 'update_individual', on: :collection      
    end
    resources :weekly_schedules do
        post 'edit_individual', on: :collection 
        put 'update_individual', on: :collection
    end
  end

  mount Dashing::Engine, at: Dashing.config.engine_path

  root to: "sessions#new"

end

app/models/airplane.rb
class Airplane < ActiveRecord::Base
	self.primary_key = 'reg'
	has_many :turns, primary_key: 'reg'
	before_save :add_cabin
	def add_cabin
		self.total_capacity = self.j_capacity + self.w_capacity + self.y_capacity
	end
end

app/models/airport.rb
class Airport < ActiveRecord::Base
	self.primary_key = 'code'
	has_many :operations, primary_key: "code"
	has_many :tickers, primary_key: "code"
	has_many :employees, primary_key: "code"
	has_many :metrics, primary_key: "code"
	has_many :weekly_schedules, through: :employees
	has_secure_password
end

app/models/arrival.rb
class Arrival < ActiveRecord::Base
	belongs_to :flight, class_name: "Flight",
						foreign_key: "flight_number"
	has_one :turn
	before_save :add_cabin
	before_update :add_cabin

	def add_cabin
		self.total_booked = self.j_booked + self.w_booked + self.y_booked
	end
end

app/models/departure.rb
class Departure < ActiveRecord::Base
	attr_accessor :j_capacity, :w_capacity, :y_capacity, :total_capacity, :j_hash
	
	after_find :determine_capacity
	before_save :add_cabin
	before_update :add_cabin

	belongs_to :flight, class_name: "Flight",
						foreign_key: "flight_number"
	has_one :turn
	has_one :airplane, through: :turn

	def determine_capacity
		if self.airplane.blank? == false
			self.j_capacity = self.airplane.j_capacity
			self.w_capacity = self.airplane.w_capacity
			self.y_capacity = self.airplane.y_capacity
			self.total_capacity = self.j_capacity + self.w_capacity + self.y_capacity
		end
	end

	def add_cabin
		self.total_booked = self.j_booked + self.w_booked + self.y_booked
		self.total_meals = self.j_meals + self.w_meals + self.y_meals
		self.total_sby = self.j_sby + self.w_sby + self.y_sby	
	end


end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :airport
  has_one :weekly_schedule
  has_many :positions, through: :weekly_schedules, foreign_key: :monday_id
  has_many :positions, through: :weekly_schedules, foreign_key: :tuesday_id
  has_many :positions, through: :weekly_schedules, foreign_key: :wednesday_id
  has_many :positions, through: :weekly_schedules, foreign_key: :thursday_id
  has_many :positions, through: :weekly_schedules, foreign_key: :friday_id
  has_many :positions, through: :weekly_schedules, foreign_key: :saturday_id
  has_many :positions, through: :weekly_schedules, foreign_key: :sunday_id
end

app/models/flight.rb
class Flight < ActiveRecord::Base
	self.primary_key = 'flight_number'
	has_many :flight_schedules
	has_many :adhoc_cancellations, through: :flight_schedules
	has_many :departures, primary_key: 'flight_number'
	has_many :arrivals, primary_key: 'flight_number'
	has_many :flight_schedules, primary_key: 'flight_number'
end

app/models/flight_schedule.rb
class FlightSchedule < ActiveRecord::Base
	belongs_to :flight, class_name: "Flight",
						foreign_key: "flight_number"	
	has_many :adhoc_cancellations
end

app/models/metric.rb
class Metric < ActiveRecord::Base
	belongs_to :airport
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :turn_id
end

app/models/operation.rb
class Operation < ActiveRecord::Base
	belongs_to :airport
	has_many :turns
end

app/models/position.rb
class Position < ActiveRecord::Base
	has_many :weekly_schedules, foreign_key: :monday_id
	has_many :weekly_schedules, foreign_key: :tuesday_id
	has_many :weekly_schedules, foreign_key: :wednesday_id
	has_many :weekly_schedules, foreign_key: :thursday_id
	has_many :weekly_schedules, foreign_key: :friday_id
	has_many :weekly_schedules, foreign_key: :saturday_id
	has_many :weekly_schedules, foreign_key: :sunday_id
end

app/models/ticker.rb
class Ticker < ActiveRecord::Base
	belongs_to :airport
end

app/models/turn.rb
class Turn < ActiveRecord::Base
	belongs_to :airplane, class_name: "Airplane",
						 foreign_key: "reg"
	belongs_to :airport, class_name: "Airport",
						 foreign_key: "airport"
	belongs_to :departure
	belongs_to :arrival
	belongs_to :operation
end

app/models/weekly_schedule.rb
class WeeklySchedule < ActiveRecord::Base

	after_create :set_unassigned
  belongs_to :employee
  belongs_to :monday,  class_name: "Position", foreign_key: "monday_id"
  belongs_to :tuesday,  class_name: "Position"
  belongs_to :wednesday,  class_name: "Position"
  belongs_to :thursday,  class_name: "Position"
  belongs_to :friday,  class_name: "Position"
  belongs_to :saturday,  class_name: "Position"
  belongs_to :sunday,  class_name: "Position"


  def set_unassigned
  	self.monday = Position.where(name:"UNASSIGNED").first
  	self.tuesday = Position.where(name:"UNASSIGNED").first
  	self.wednesday = Position.where(name:"UNASSIGNED").first
  	self.thursday = Position.where(name:"UNASSIGNED").first
  	self.friday = Position.where(name:"UNASSIGNED").first
  	self.saturday = Position.where(name:"UNASSIGNED").first
  	self.sunday = Position.where(name:"UNASSIGNED").first
  	self.save
  end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  before_action :set_turn, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  respond_to :html

  def index
    @turns = Turn.all
    respond_with(@turns)
  end

  def show
    respond_with(@turn)
  end

  def new
    @turn = Turn.new
    respond_with(@turn)
  end

  def edit
  end

  def create
    @turn = Turn.new(turn_params)
    @turn.save
    respond_with(@turn)
  end

  def update
    @turn.update(turn_params)
    respond_with(@turn)
  end

  def destroy
    @turn.destroy
    respond_with(@turn)
  end

  private
    def set_turn
      @turn = Turn.find(params[:id])
    end

    def turn_params
      params.require(:turn).permit(:reg, :arrival, :departure, :gate)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/arrivals_helper.rb
module ArrivalsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(airport)
    session[:code] = airport.code
  end

  def log_out
    session.delete(:code)
    @current_airport = nil
  end


  def current_airport
    @current_airport ||= Airport.find_by(code: session[:code])
  end

  def logged_in?
    !current_airport.nil?
  end
end

app/helpers/tickers_helper.rb
module TickersHelper
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/views/turns/_form.html.erb
<%= fields_for "turn", turn do |turn| %>


  <div class="field">
    <%= turn.label :aircraft %><br>
    <%= turn.text_field :aircraft %>
  </div>
  <div class="field">
    <%= turn.label :arrival %><br>
    <%= turn.text_field :arrival %>
  </div>
  <div class="field">
    <%= turn.label :departure %><br>
    <%= turn.text_field :departure %>
  </div>
  <div class="field">
    <%= turn.label :gate %><br>
    <%= turn.text_field :gate %>
  </div>
  <div class="actions">
    <%= turn.submit %>
  </div>
<% end %>

app/views/turns/edit.html.erb
<h1>Editing Turn</h1>

<%= render 'form' %>

<%= link_to 'Show', @turn %> |
<%= link_to 'Back', turns_path %>

app/views/turns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Turns</h1>

<table>
  <thead>
    <tr>
      <th>Aircraft</th>
      <th>Arrival</th>
      <th>Departure</th>
      <th>Gate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turns.each do |turn| %>
      <tr>
        <td><%= turn.aircraft %></td>
        <td><%= turn.arrival %></td>
        <td><%= turn.departure %></td>
        <td><%= turn.gate %></td>
        <td><%= link_to 'Show', turn %></td>
        <td><%= link_to 'Edit', edit_turn_path(turn) %></td>
        <td><%= link_to 'Destroy', turn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turn', new_turn_path %>

app/views/turns/new.html.erb
<h1>New Turn</h1>

<%= render 'form' %>

<%= link_to 'Back', turns_path %>

app/views/turns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aircraft:</strong>
  <%= @turn.aircraft %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @turn.arrival %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @turn.departure %>
</p>

<p>
  <strong>Gate:</strong>
  <%= @turn.gate %>
</p>

<%= link_to 'Edit', edit_turn_path(@turn) %> |
<%= link_to 'Back', turns_path %>