config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :weekly_schedules

  resources :airports do
    resources :positions
    resources :operations do
      get 'send_to_dashboard', on: :member
    end
    resources :adhoc_cancellations
    resources :flights
    resources :flight_schedules
    resources :turns
    resources :arrivals
    resources :airplanes
    resources :departures
    resources :employees
    resources :metrics
    resources :tickers do 
      post 'edit_individual', on: :collection 
      put 'update_individual', on: :collection      
    end
    resources :weekly_schedules do
        post 'edit_individual', on: :collection 
        put 'update_individual', on: :collection
    end
  end

  mount Dashing::Engine, at: Dashing.config.engine_path

  root to: "sessions#new"

end

app/models/airplane.rb
class Airplane < ActiveRecord::Base
	self.primary_key = 'reg'
	has_many :turns, primary_key: 'reg'
	before_save :add_cabin
	def add_cabin
		self.total_capacity = self.j_capacity + self.w_capacity + self.y_capacity
	end
end

app/models/airport.rb
class Airport < ActiveRecord::Base
	self.primary_key = 'code'
	has_many :operations, primary_key: "code"
	has_many :tickers, primary_key: "code"
	has_many :employees, primary_key: "code"
	has_many :metrics, primary_key: "code"
	has_many :weekly_schedules, through: :employees
	has_secure_password
end

app/models/arrival.rb
class Arrival < ActiveRecord::Base
	belongs_to :flight, class_name: "Flight",
						foreign_key: "flight_number"
	has_one :turn
	before_save :add_cabin
	before_update :add_cabin

	def add_cabin
		self.total_booked = self.j_booked + self.w_booked + self.y_booked
	end
end

app/models/departure.rb
class Departure < ActiveRecord::Base
	attr_accessor :j_capacity, :w_capacity, :y_capacity, :total_capacity, :j_hash
	
	after_find :determine_capacity
	before_save :add_cabin
	before_update :add_cabin

	belongs_to :flight, class_name: "Flight",
						foreign_key: "flight_number"
	has_one :turn
	has_one :airplane, through: :turn

	def determine_capacity
		if self.airplane.blank? == false
			self.j_capacity = self.airplane.j_capacity
			self.w_capacity = self.airplane.w_capacity
			self.y_capacity = self.airplane.y_capacity
			self.total_capacity = self.j_capacity + self.w_capacity + self.y_capacity
		end
	end

	def add_cabin
		self.total_booked = self.j_booked + self.w_booked + self.y_booked
		self.total_meals = self.j_meals + self.w_meals + self.y_meals
		self.total_sby = self.j_sby + self.w_sby + self.y_sby	
	end


end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :airport
  has_one :weekly_schedule
  has_many :positions, through: :weekly_schedules, foreign_key: :monday_id
  has_many :positions, through: :weekly_schedules, foreign_key: :tuesday_id
  has_many :positions, through: :weekly_schedules, foreign_key: :wednesday_id
  has_many :positions, through: :weekly_schedules, foreign_key: :thursday_id
  has_many :positions, through: :weekly_schedules, foreign_key: :friday_id
  has_many :positions, through: :weekly_schedules, foreign_key: :saturday_id
  has_many :positions, through: :weekly_schedules, foreign_key: :sunday_id
end

app/models/flight.rb
class Flight < ActiveRecord::Base
	self.primary_key = 'flight_number'
	has_many :flight_schedules
	has_many :adhoc_cancellations, through: :flight_schedules
	has_many :departures, primary_key: 'flight_number'
	has_many :arrivals, primary_key: 'flight_number'
	has_many :flight_schedules, primary_key: 'flight_number'
end

app/models/flight_schedule.rb
class FlightSchedule < ActiveRecord::Base
	belongs_to :flight, class_name: "Flight",
						foreign_key: "flight_number"	
	has_many :adhoc_cancellations
end

app/models/metric.rb
class Metric < ActiveRecord::Base
	belongs_to :airport
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :turn_id
end

app/models/operation.rb
class Operation < ActiveRecord::Base
	belongs_to :airport
	has_many :turns
end

app/models/position.rb
class Position < ActiveRecord::Base
	has_many :weekly_schedules, foreign_key: :monday_id
	has_many :weekly_schedules, foreign_key: :tuesday_id
	has_many :weekly_schedules, foreign_key: :wednesday_id
	has_many :weekly_schedules, foreign_key: :thursday_id
	has_many :weekly_schedules, foreign_key: :friday_id
	has_many :weekly_schedules, foreign_key: :saturday_id
	has_many :weekly_schedules, foreign_key: :sunday_id
end

app/models/ticker.rb
class Ticker < ActiveRecord::Base
	belongs_to :airport
end

app/models/turn.rb
class Turn < ActiveRecord::Base
	belongs_to :airplane, class_name: "Airplane",
						 foreign_key: "reg"
	belongs_to :airport, class_name: "Airport",
						 foreign_key: "airport"
	belongs_to :departure
	belongs_to :arrival
	belongs_to :operation
end

app/models/weekly_schedule.rb
class WeeklySchedule < ActiveRecord::Base

	after_create :set_unassigned
  belongs_to :employee
  belongs_to :monday,  class_name: "Position", foreign_key: "monday_id"
  belongs_to :tuesday,  class_name: "Position"
  belongs_to :wednesday,  class_name: "Position"
  belongs_to :thursday,  class_name: "Position"
  belongs_to :friday,  class_name: "Position"
  belongs_to :saturday,  class_name: "Position"
  belongs_to :sunday,  class_name: "Position"


  def set_unassigned
  	self.monday = Position.where(name:"UNASSIGNED").first
  	self.tuesday = Position.where(name:"UNASSIGNED").first
  	self.wednesday = Position.where(name:"UNASSIGNED").first
  	self.thursday = Position.where(name:"UNASSIGNED").first
  	self.friday = Position.where(name:"UNASSIGNED").first
  	self.saturday = Position.where(name:"UNASSIGNED").first
  	self.sunday = Position.where(name:"UNASSIGNED").first
  	self.save
  end
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: [:show, :edit, :update, :destroy]
  before_filter :authorize #, :except => [:index]

  respond_to :html

  def index
    @airports = Airport.all
    respond_with(@airports)
  end

  def show
    respond_with(@airport)
  end

  def new
    @airport = Airport.new
    respond_with(@airport)
  end

  def edit
  end

  def create
    @airport = Airport.new(airport_params)
    @airport.save
    respond_with(@airport)
  end

  def update
    @airport.update(airport_params)
    respond_with(@airport)
  end

  def destroy
    @airport.destroy
    respond_with(@airport)
  end

  private
    def set_airport
      @airport = Airport.find(params[:id])
    end

    def airport_params
      params.require(:airport).permit(:code, :name, :city, :country, :latlon, :timezone)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/arrivals_helper.rb
module ArrivalsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(airport)
    session[:code] = airport.code
  end

  def log_out
    session.delete(:code)
    @current_airport = nil
  end


  def current_airport
    @current_airport ||= Airport.find_by(code: session[:code])
  end

  def logged_in?
    !current_airport.nil?
  end
end

app/helpers/tickers_helper.rb
module TickersHelper
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/views/airports/_form.html.erb
<%= form_for(@airport) do |f| %>
  <% if @airport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
      <% @airport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :latlon %><br>
    <%= f.text_field :latlon %>
  </div>
  <div class="field">
    <%= f.label :timezone %><br>
    <%= f.text_field :timezone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<h1>Editing Airport</h1>

<%= render 'form' %>

<%= link_to 'Show', @airport %> |
<%= link_to 'Back', airports_path %>

app/views/airports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Airports</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>City</th>
      <th>Country</th>
      <th>Latlon</th>
      <th>Timezone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airports.each do |airport| %>
      <tr>
        <td><%= airport.code %></td>
        <td><%= airport.name %></td>
        <td><%= airport.city %></td>
        <td><%= airport.country %></td>
        <td><%= airport.latlon %></td>
        <td><%= airport.timezone %></td>
        <td><%= link_to 'Show', airport %></td>
        <td><%= link_to 'Edit', edit_airport_path(airport) %></td>
        <td><%= link_to 'Destroy', airport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airport', new_airport_path %>

app/views/airports/new.html.erb
<h1>New Airport</h1>

<%= render 'form' %>

<%= link_to 'Back', airports_path %>

app/views/airports/show.html.erb
<p id="notice"><%= notice %></p>
<button><%= link_to 'Manage Staff Schedule', airport_weekly_schedules_path(airport_id: @airport.code) %></button>
<button><%= link_to 'Manage Operations', airport_operations_path(airport_id: @airport.code) %> </button>
<p>
  <strong>Code:</strong>
  <%= @airport.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @airport.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @airport.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @airport.country %>
</p>

<p>
  <strong>Latlon:</strong>
  <%= @airport.latlon %>
</p>

<p>
  <strong>Timezone:</strong>
  <%= @airport.timezone %>
</p>

<%= link_to 'Edit', edit_airport_path(@airport) %> |
<%= link_to 'Back', airports_path %>