config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :weekly_schedules

  resources :airports do
    resources :positions
    resources :operations do
      get 'send_to_dashboard', on: :member
    end
    resources :adhoc_cancellations
    resources :flights
    resources :flight_schedules
    resources :turns
    resources :arrivals
    resources :airplanes
    resources :departures
    resources :employees
    resources :metrics
    resources :tickers do 
      post 'edit_individual', on: :collection 
      put 'update_individual', on: :collection      
    end
    resources :weekly_schedules do
        post 'edit_individual', on: :collection 
        put 'update_individual', on: :collection
    end
  end

  mount Dashing::Engine, at: Dashing.config.engine_path

  root to: "sessions#new"

end

app/models/operation.rb
class Operation < ActiveRecord::Base
	belongs_to :airport
	has_many :turns
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  respond_to :html

  def index
    @airport = Airport.find(params[:airport_id])
    @operations = @airport.operations.all
    respond_with(@operations)
  end

  def show
    @airport = Airport.find(params[:airport_id])
    @operation = @airport.operations.find(params[:id])
    respond_with(@operation)
  end

  def new
    @airport = Airport.find(params[:airport_id])
    date = Date.today
    @operation = @airport.operations.new(date: date)
    departure_list = []
    departure_schedule = []
    arrival_list = []
    arrival_schedule = []
    @turns_arr = []
    ac_list_arr = []
    @turns = []

    Flight.where(origin: @airport.code).each do |x|
      FlightSchedule.where(flight_number: x).where("start_date < ? AND end_date > ?", date, date).each do |departure|
        departure_list.push(x)
        departure_schedule.push(departure)
      end
    end

    Flight.where(destination: @airport.code).each do |x|
      FlightSchedule.where(flight_number: x).where("start_date < ? AND end_date > ?", date, date).each do |arrival|
        arrival_list.push(x)
        arrival_schedule.push(arrival)
      end
    end

    arrival_schedule.each do |arrival|
      plane_list = Airplane.where(ac_type: arrival.ac_type)
      ac_list_arr.push(plane_list)
    end

    arrival_list.count.times do |x|
      turn = @operation.turns.new(date: @operation.date)
      turn.airport = @operation.airport
      turn.save
      departure = (turn.departure = Departure.create)
      departure.flight = departure_list[x]
      departure.std = departure_schedule[x].departure
      departure.save
      arrival = (turn.arrival = Arrival.create)
      arrival.flight = arrival_list[x]
      arrival.sta = arrival_schedule[x].arrival
      arrival.save
      turn_item = Hash.new
      turn_item["turn"] = turn
      turn_item["departure"] = departure
      turn_item["departure_sked"] = departure_schedule[x]
      turn_item["arrival"] = arrival
      turn_item["arrival_sked"] = arrival_schedule[x]
      turn_item["aircraft_options"] = ac_list_arr[x]
      @turns_arr.push(turn_item)
      @turns.push(turn)
    end

  end

  def edit
    @airport = Airport.find(params[:airport_id])
    @operation = Operation.find(params[:id])
    @turns = @operation.turns
  end

  def create
    @airport = Airport.find(params[:airport_id])
    @operation = Operation.find(params[:id])
    params[:turn].each do |key, value|
      turn = Turn.find(key)
      turn.gate = value[:gate]
      airplane =  Airplane.find(value[:airplane])
      turn.airplane = airplane
      turn.save
    end
    Arrival.update(params[:arrival].keys, params[:arrival].values)
    Departure.update(params[:departure].keys, params[:departure].values)
    respond_with(@operation)
  end

  def update
    @airport = Airport.find(params[:airport_id])
    @operation = Operation.find(params[:id])
    params[:turn].each do |key, value|
      turn = Turn.find(key)
      turn.gate = value[:gate]
      airplane =  Airplane.find(value[:airplane])
      turn.airplane = airplane
      turn.save
    end
    Arrival.update(params[:arrival].keys, params[:arrival].values)
    Departure.update(params[:departure].keys, params[:departure].values)
    respond_to do |f|
      f.html { redirect_to airport_operation_path(@airport,@operation), notice: 'Daily Operation Created' }
    end
  end

  def destroy
    @operation.destroy
    respond_with(@operation)
  end

  def determine_turns
    @turn = @operation.turns.new
    @turn.save
  end

  def send_to_dashboard
    @airport = Airport.find(params[:airport_id])
    @operation = Operation.find(params[:id])
    @turns = @operation.turns

    @sked = @airport.weekly_schedules
    positions = Hash.new
    Position.all.each do |key|
      position_sked = @sked.where(:"#{@operation.date.strftime("%A").downcase}_id" => key.id.to_s)
      arr = positions["#{key.name.downcase}"] = []
      position_sked.each_with_index do |x, idx|
        arr.push((x.employee.first_name + " " + x.employee.last_name))
      end
    end

    Dashing.send_event "positions_#{@airport.code.downcase}", {
      supervisor: positions["supervisor"], 
      tco: positions["tco/flight prep"], 
      fmu: positions["fmu"], 
      ticketer: positions["ticketer/cashier"], 
      baggage: positions["baggage"], 
      clubhouse: positions["lounge"], 
      arrival_lead: positions["arrival lead"], 
      curb_y: positions["curb / y"], 
      gate_lead: positions["gate lead"], 
      j_cls: positions["j-cls"], 
      w_cls: positions["w-cls"], 
      y_cls: positions["y-cls"], 
      lobby: positions["lobby"], 
      bag_drop: positions["bag drop"]
    }

    @turns.each_with_index do |turn, index|
      @departure = turn.departure
      @arrival = turn.arrival
      @airplane = turn.airplane

      Dashing.send_event "flifo_#{index}_#{@airport.code.downcase}", {
        inbound_flight_number: @arrival.flight_number,
        outbound_flight_number: @departure.flight_number,
        registration: @airplane.reg,
        aircraft_type: @airplane.ac_type ,
        aircraft_name: @airplane.name ,
        j: @airplane.j_capacity,
        w: @airplane.w_capacity,
        y: @airplane.y_capacity,
        tob: @airplane.total_capacity,
        gate: turn.gate 
        }
      Dashing.send_event "arrival_#{index}_#{@airport.code.downcase}", {
        inbound_flight_number: @arrival.flight_number,
        sta: @arrival.sta.strftime("%H:%M"), 
        eta: @arrival.eta.strftime("%H:%M"),
        captain: @arrival.captain,
        fsm: @arrival.fsm,
        j: @arrival.j_booked,
        w: @arrival.w_booked,
        y: @arrival.y_booked,
        tob: @arrival.total_booked,
        specials: @arrival.specials
      } 
      Dashing.send_event("departure_#{index}_#{@airport.code.downcase}", {
        flight_number: @departure.flight_number,
        std: @departure.std.strftime("%H:%M"),
        etd: @departure.etd.strftime("%H:%M"),
        captain: @departure.captain,
        fsm: @departure.fsm,
        j_booked: @departure.j_booked,
        w_booked: @departure.w_booked,
        y_booked: @departure.y_booked,
        total_booked: @departure.total_booked,
        j_meals: @departure.j_meals,
        w_meals: @departure.w_meals,
        y_meals: @departure.y_meals,
        total_meals: @departure.total_meals,
        j_staff: @departure.j_sby,
        w_staff: @departure.w_sby,
        y_staff: @departure.y_sby,
        total_staff: @departure.total_sby,
        specials: @departure.specials 
        })
      Dashing.send_event("notes_#{index}_#{@airport.code}", { notes_content: "NOTES" })
    end
    redirect_to airport_operations_path(@airport), notice: 'Sent to Dashboard' 
  end


  private
    def set_operation
      @operation = Operation.find(params[:id])
    end

    def operation_params
      params.require(:operation).permit(:airport_id, :date, :staff_assignment)
    end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= form_for [@airport, @operation] do |o| %>
<% counter = 0 %>
<div class="row clearfix">
  <div class="col-md-1 column">
    <h3></h3>
  </div>
  <div class="col-md-11 column">
    <div class="field">
      <%= @airport.name %><br>
    </div>
    <div class="field">
      <%= o.label :date %><br>
      <%= o.date_select :date %>
    </div>




  <% @turns.each_with_index do |turn, index| %>
  <div class="row clearfix">
    <div class="col-md-1 column">
      <h3></h3>
    </div>
    <div class="col-md-1 column">
            <h3>turn</h3>
      <%= fields_for "turn[]", turn do |turn| %>


      <div class="field">
      <div class="field">
    <%= turn.label :noop %><br>
    <%= turn.check_box :noop %>
    
  </div>
        <%= turn.label :airplane %><br>
        <%= turn.collection_select :airplane, @turns_arr.select{|key, hash| key["turn"].id == @turns[counter].id}.first["aircraft_options"], :reg, :reg %>
      </div>
      <div class="field">
        <%= turn.label :gate %><br>
        <%= turn.text_field :gate %>
      </div>
      <% end %>

    </div>
    <div class="col-md-1 column">
      <h3></h3>
    </div>

    <div class="col-md-4 column" style="border-left:1px solid #000">
            <h3>Arrival <%= index + 1 %></h3>
      <%= fields_for "arrival[]", turn.arrival do |arrival| %>

      <div class="field">
        <%= arrival.label :flight_number %><br>
        <%= arrival.text_field :flight_number %>
      </div>
      <table>
        <tr>
          <td>
            <div class="field">
              <%= arrival.label :sta %><br>
              <%= arrival.time_select :sta %>
            </div>
          </td>
          <td>
            <div class="field">
              <%= arrival.label :eta %><br>
              <%= arrival.time_select :eta %>
            </div>
          </td>
          <td>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <td>
            <div class="field">
              <%= arrival.label :captain %><br>
              <%= arrival.text_field :captain %>
            </div>
          </td>
          <td>
            <div class="field">
              <%= arrival.label :fsm %><br>
              <%= arrival.text_field :fsm %>
            </div>
          </td>
          <td>
          </td>

        </tr>
      </table>
      <table>
        <tr>
          <td>
            <div class="field">
              <%= arrival.label :j_booked %><br>
              <%= arrival.text_field :j_booked %>
            </div>
          </td>
          <td>
            <div class="field">
              <%= arrival.label :w_booked %><br>
              <%= arrival.text_field :w_booked %>
            </div>
          </td>
          <td>
            <div class="field">
              <%= arrival.label :y_booked %><br>
              <%= arrival.text_field :y_booked %>
            </div>
          </td>
        </tr>
      </table>
      <div class="field">
        <%= arrival.label :specials %><br>
        <%= arrival.text_area :specials %>
      </div>
      <% end %>
    </div>
    <div class="col-md-4 column" style="border-left:1px solid #000">
            <h3>Departure</h3>
      <%= fields_for "departure[]", turn.departure do |departure| %>

      <div class="field">
        <%= departure.label :flight_number %><br>
        <%= departure.text_field :flight_number %>
      </div>
      <table>
        <tr>
          <td>
            <div class="field">
              <%= departure.label :std %><br>
              <%= departure.time_select :std %>
            </div>
          </td>
          <td>
            <div class="field">
              <%= departure.label :etd %><br>
              <%= departure.time_select :etd %>
            </div>
          </td>
          <td>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <td>
            <div class="field">
              <%= departure.label :captain %><br>
              <%= departure.text_field :captain %>
            </div>
          </td>
          <td>
            <div class="field">
              <%= departure.label :fsm %><br>
              <%= departure.text_field :fsm %>
            </div>
          </td>
          <td>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <td>
            <div class="field">
              <%= departure.label :j_booked %><br>
              <%= departure.text_field :j_booked %>
            </div>
          </td>
          <td>
            <div class="field">
              <%= departure.label :w_booked %><br>
              <%= departure.text_field :w_booked %>
            </div>
          </td>
          <td>
            <div class="field">
              <%= departure.label :y_booked %><br>
              <%= departure.text_field :y_booked %>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <div class="field">
              <%= departure.label :j_meals %><br>
              <%= departure.text_field :j_meals %>
            </div>
          </td>
          <td>
            <div class="field">
              <%= departure.label :w_meals %><br>
              <%= departure.text_field :w_meals %>
            </div>
          </td>
          <td>
            <div class="field">
              <%= departure.label :y_meals %><br>
              <%= departure.text_field :y_meals %>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <div class="field">
              <%= departure.label :j_sby %><br>
              <%= departure.text_field :j_sby %>
            </div>
          </td>
          <td>
            <div class="field">
              <%= departure.label :w_sby %><br>
              <%= departure.text_field :w_sby %>
            </div>
          </td>
          <td>
            <div class="field">
              <%= departure.label :y_sby %><br>
              <%= departure.text_field :y_sby %>
            </div>
          </td>
        </tr>
      </table>
      <div class="field">
        <%= departure.label :specials %><br>
        <%= departure.text_area :specials %>
      </div>
      <% end %>

    </div>
  </div>
  <hr>
  <% end %>
  <div class="actions">



    <%= o.submit %>

    <div class="actions">

      <% end %>

app/views/operations/edit.html.erb
<h1>Editing Operation</h1>

<%= render 'form' %>

<%= link_to 'Show', airport_operation_path(id: @operation.id) %> |
<%= link_to 'Back', airport_operations_path %>

app/views/operations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Operations</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Date</th>
      <th>Staff assignment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%= operation.airport_id %></td>
        <td><%= operation.date %></td>
        <td><%= operation.staff_assignment %></td>
        <td><%= link_to 'Show', airport_operation_path(id: operation.id) %></td>
        <td><%= link_to 'Send to Dashboard', send_to_dashboard_airport_operation_path(id: operation.id) %> </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operation', new_airport_operation_path %>

app/views/operations/new.html.erb
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			</div><h1>New Operation</h1>
		</div>
	</div>

	<%= render 'form' %>

	<div class="row clearfix">
		<div class="col-md-12 column">
			<%= link_to 'Back', airport_operations_path %>
		</div>
	</div>
</div>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @operation.airport_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @operation.date %>
</p>

<p>
  <strong>Staff assignment:</strong>
  <%= @operation.staff_assignment %>
</p>

<%= link_to 'Edit', edit_airport_operation_path(params[:airport_id], @operation) %> |
<%= link_to 'Back', airport_operations_path %>